Repository 0Neokun0/upcolor-2.0, pull requests merged in 2022-12, with the labels that each got.

#122 色々
  client/src/components/molecules/NavbarMenu.jsx
  client/src/components/molecules/classNewsCard.jsx
  client/src/components/molecules/classNewsFeedCard.jsx
  client/src/components/molecules/companyCard.jsx
  client/src/components/molecules/companyListProfileCard.jsx
  client/src/components/molecules/mainMenuProfileCard.jsx
  client/src/components/molecules/newsCard.jsx
  client/src/components/molecules/post.jsx
  client/src/components/molecules/profileCard.jsx
  client/src/components/molecules/profileOnFeed.jsx
  client/src/components/molecules/profilePost.jsx
  client/src/components/molecules/studentListProfileCard.jsx
  client/src/components/molecules/viewFeed.jsx
  client/src/components/organisms/classNewsFeedForm.jsx
  client/src/components/organisms/classNewsFeedHeader.jsx
  client/src/components/organisms/mainMenu.jsx
  client/src/components/organisms/newsForm.jsx
  client/src/components/organisms/postBox.jsx
  client/src/components/organisms/replyModal.jsx
  client/src/components/organisms/sendPost.jsx
  client/src/components/organisms/teacherNewsHeader.jsx
  client/src/components/pages/student/profile.jsx
  client/src/components/pages/student/profileEdit.jsx
  client/src/components/templates/homeLayout.jsx
Labels: 完成

#125 mainmenuでクラスニューズ置いただけ
  client/src/App.js
  client/src/components/pages/student/studentHome.jsx
Labels: 完成

#126 teamで技術入力するやつ
  client/src/components/pages/student/teamWork.jsx
  client/src/components/pages/viewTeamWork.jsx
  server/api/teamWork.js
Labels: 完成

#109 グループチャットicon追加(未完成)
  client/src/components/organisms/groupChat.jsx
  client/src/components/organisms/groupList.jsx
  client/src/components/organisms/groupMembers.jsx
  client/src/components/templates/groupChatLayout.jsx
  client/src/components/templates/groupLayout.jsx
Labels: 完成

#129 個チャ双方向通信実装
  client/src/components/molecules/chatForm.jsx
  client/src/components/molecules/chatNew.jsx
  client/src/components/molecules/userButton.jsx
  client/src/components/organisms/privateChatBox.jsx
  client/src/components/organisms/privateChatUsers.jsx
  client/src/components/pages/student/privateChat.jsx
  server/api/account.js
  server/api/privateChat.js
  server/api/socket.js
  server/server.js
  upcolor.sql
Labels: 完成

#127 教員ニューズカード並び綺麗にすると投稿ごwindow.refresh
  client/src/components/molecules/newsCard.jsx
  client/src/components/pages/teacher/teacherNews.jsx
Labels: 完成

#130 初期セレクト、更新時スクロール、メニューの実装
  client/src/components/molecules/chatNew.jsx
  client/src/components/molecules/userButton.jsx
  client/src/components/organisms/privateChatBox.jsx
  client/src/components/organisms/privateChatDrawer.jsx
  client/src/components/organisms/privateChatUsers.jsx
  client/src/components/pages/student/privateChat.jsx
  client/src/components/templates/privateChatLayout.jsx
  server/api/privateChat.js
Labels: 完成

#138 ボタン追加イメージ追加イメージボーダー等
  client/src/components/molecules/companyListProfileCard.jsx
  client/src/components/molecules/companyPageTitle.jsx
  client/src/components/molecules/mainMenuCompanyCard.jsx
  client/src/components/organisms/companyDetailsTab.jsx
  client/src/components/organisms/listDisplayBox.jsx
  client/src/components/pages/company/companyHome.jsx
  client/src/components/pages/student/companyList.jsx
  client/src/components/pages/student/studentList.jsx
  client/src/components/pages/viewCompanyPage.jsx
Labels: 完成

#137 クラスニュース復活
  client/src/App.js
  client/src/components/organisms/classNewsCardList.jsx
Labels: 完成

#142 お気に入り投稿閲覧と戻るボタン
  client/src/components/molecules/viewFeed.jsx
  client/src/components/organisms/feedDetail.jsx
  client/src/components/pages/student/profile.jsx
  client/src/components/pages/student/studentHome.jsx
  client/src/components/templates/homeLayout.jsx
  server/api/post.js
Labels: 完成

#143 投稿の削除 *DBの変更有
  client/src/components/molecules/viewFeed.jsx
  client/src/components/organisms/feedDetail.jsx
  client/src/components/pages/student/studentHome.jsx
  client/src/components/templates/homeLayout.jsx
  server/api/post.js
  upcolor.sql
Labels: 完成, DB変更

#141 team list 戻るボタン
  client/src/components/organisms/listDisplayBox.jsx
  client/src/components/pages/student/studentList.jsx
  client/src/components/pages/student/teamList.jsx
Labels: 完成

#147 Revert "Revert "Revert "Revert "投稿の削除 *DBの変更有""""
  client/src/components/molecules/viewFeed.jsx
  client/src/components/organisms/feedDetail.jsx
  client/src/components/pages/student/studentHome.jsx
  client/src/components/templates/homeLayout.jsx
  server/api/post.js
  upcolor.sql
Labels: bug

#155 developページの修正イコンとusertypesの書き方
  client/src/App.js
  client/src/components/molecules/NavbarMenu.jsx
  client/src/components/organisms/header.jsx
  client/src/components/pages/student/companyList.jsx
  client/src/components/pages/teacher/teacherHome.jsx
Labels: 完成

#160 teamworkView-teamworkリストなどでバックボタン追加
  client/src/components/molecules/teamInfoCard.jsx
  client/src/components/pages/student/companyList.jsx
  client/src/components/pages/student/teamList.jsx
  client/src/components/pages/student/teamWork.jsx
  client/src/components/pages/viewTeamWork.jsx
  client/src/components/templates/teamWorkLayout.jsx
Labels: 完成

#164 Feature header menus changing with different users
  client/src/App.js
  client/src/components/molecules/companyListProfileCard.jsx
  client/src/components/molecules/companyPageTitle.jsx
  client/src/components/molecules/mainMenuCompanyCard.jsx
  client/src/components/organisms/companyNewsHeader.jsx
  client/src/components/organisms/signInBox.jsx
  client/src/components/organisms/signUpBox.jsx
  client/src/components/pages/company/companyHome.jsx
  client/src/components/pages/teacher/develop/developHome.jsx
  server/api/company.js
Labels: 完成
